spring:
#  profiles:
#    active: local
#  datasource:
#    data: classpath:data-h2.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true

  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true

server.error:
  include-exception: false
  include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부
  path: '/error' # 오류 응답을 처리할 Handler의 경로
  whitelabel.enabled: true # 서버 오류 발생시 브라우저에 보여줄 기본 페이지 생성 여부